### ISSUE TITLE
tracking.py

### ISSUE THREAD

**Issue by luoluo-gif** [Sierkinhane/human_tracker#4]
How to get the "latest_h_f.pt" on  "tracking.py", line 38? I ran "main.py" myself, but didn't get "latest_h_f.pt",how did it appear?

**Comment by Sierkinhane** [comment]
download yolov3 and centerloss weights. https://pan.baidu.com/s/1ECT_CA8UlgsMlzvBcVwr2w pw:om7k
python tracking.py the output will be stored in videos/output

**Comment by wuxiaolianggit** [comment]
请问一下大佬，这个项目耗时性能如何？ @Sierkinhane

**Comment by Sierkinhane** [comment]
单目标追踪有18FPS左右
